spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=orders
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/db.changelog-master.xml

server:
  port: 8082