spring:
  application:
    name: customer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer
    username: postgres
    password: postgres 
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: classpath:db/db.changelog-master.xml


server:
  port: 8081
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8070/eureka/
      
## Configuring info endpoint
info:
  app:
    name: Customer Microservice
    description: Customer Application
    version: 1.0.0
          
management:
  endpoint:
    shutdown:
      enabled: true