spring:
  application:
    name: configserver
    
  profiles:
    active:
    - git
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CoderTechWeb/microservice-config.git
          clone-on-start: true
          default-label: main
          
server:
  port: 8071